  version: '2'
  services:
    mongo:
      image: habitat/mongodb:latest
      hostname: "mongodb"
      environment:
        HAB_MONGODB: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''"
    national-parks:
      image: habitat/national-parks:latest
      links:
        - mongo:mongodb
      command: --peer mongodb --bind database:mongodb.default
    haproxy:
      image: habitat/haproxy:latest
      ports: 
        - "8080:8080"
        - "9631:9631"
        - "9000:9000"
      links:
        - national-parks:np
      environment:
        HAB_HAPROXY: "bind = '*:8080'\nstatus_page = true"
      command: --peer np --bind backend:national-parks.default
    
